"""autoparts initial

Revision ID: 27f635876c13
Revises: 
Create Date: 2026-08-17 11:29:04.258190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27f635876c13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('agent_quota', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('shadow_mode', sa.Boolean(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_public_token'), 'companies', ['public_token'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('agents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('system', 'general', 'specialized', name='agent_type'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'active', 'paused', 'disabled', 'failed', name='agent_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('avg_success_rate', sa.Float(), nullable=False),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_company_id'), 'agents', ['company_id'], unique=False)
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.create_table('catalog_fitments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('part_name', sa.String(length=240), nullable=False),
    sa.Column('vehicle_brand', sa.String(length=80), nullable=False),
    sa.Column('vehicle_model', sa.String(length=120), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('oem_article', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_fitments_article'), 'catalog_fitments', ['article'], unique=False)
    op.create_index(op.f('ix_catalog_fitments_company_id'), 'catalog_fitments', ['company_id'], unique=False)
    op.create_table('company_policies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('pricing_policy', sa.JSON(), nullable=True),
    sa.Column('supplier_policy', sa.JSON(), nullable=True),
    sa.Column('approval_policy', sa.JSON(), nullable=True),
    sa.Column('sales_policy', sa.JSON(), nullable=True),
    sa.Column('security_policy', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_policies_company_id'), 'company_policies', ['company_id'], unique=True)
    op.create_table('cross_references',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_article', sa.String(length=120), nullable=False),
    sa.Column('source_brand', sa.String(length=80), nullable=False),
    sa.Column('target_article', sa.String(length=120), nullable=False),
    sa.Column('target_brand', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_references_company_id'), 'cross_references', ['company_id'], unique=False)
    op.create_index(op.f('ix_cross_references_source_article'), 'cross_references', ['source_article'], unique=False)
    op.create_index(op.f('ix_cross_references_target_article'), 'cross_references', ['target_article'], unique=False)
    op.create_table('customers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_company_id'), 'knowledge_entries', ['company_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('agent_kind', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'agent_kind', 'version', name='uq_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_agent_kind'), 'prompt_versions', ['agent_kind'], unique=False)
    op.create_index(op.f('ix_prompt_versions_company_id'), 'prompt_versions', ['company_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('adapter_type', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_index(op.f('ix_suppliers_slug'), 'suppliers', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_name')
    )
    op.create_index(op.f('ix_agent_tools_agent_id'), 'agent_tools', ['agent_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_action_created', 'audit_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_events_company_created', 'audit_events', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.Enum('ai_active', 'human_active', 'paused', 'closed', name='conversation_mode'), server_default='ai_active', nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_company_id'), 'conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.Enum('short', 'long', 'knowledge', name='memory_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_agent_id'), 'memory_entries', ['agent_id'], unique=False)
    op.create_table('short_memories',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_memories_agent_id'), 'short_memories', ['agent_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('body', sa.String(length=80), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('traces',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('root_span_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_span_id'], ['trace_spans.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_company_id'), 'traces', ['company_id'], unique=False)
    op.create_index(op.f('ix_traces_conversation_id'), 'traces', ['conversation_id'], unique=False)
    op.create_table('part_requests',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=False),
    sa.Column('part_name', sa.String(length=240), nullable=False),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('collecting_data', 'ready_for_search', 'searching', 'quoted', 'approved', 'completed', 'cancelled', name='part_request_status'), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['conversation_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_requests_company_id'), 'part_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_part_requests_conversation_id'), 'part_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_part_requests_customer_id'), 'part_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_part_requests_source_message_id'), 'part_requests', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_part_requests_vehicle_id'), 'part_requests', ['vehicle_id'], unique=False)
    op.create_table('tasks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'awaiting_routing', 'completed', 'failed', 'cancelled', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('routing_decision', sa.JSON(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('replayed_from_task_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replayed_from_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_replayed_from_task_id'), 'tasks', ['replayed_from_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_trace_id'), 'tasks', ['trace_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='agent_action_risk_level'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'executed', 'failed', 'cancelled', name='agent_action_status'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_agent_actions_action_type'), 'agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_actions_agent_id'), 'agent_actions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_company_id'), 'agent_actions', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_task_id'), 'agent_actions', ['task_id'], unique=False)
    op.create_table('dead_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('exception_kind', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('dead_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_task_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replayed_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_tasks_agent_id'), 'dead_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_dead_tasks_company_id'), 'dead_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_dead_tasks_replayed_task_id'), 'dead_tasks', ['replayed_task_id'], unique=False)
    op.create_index(op.f('ix_dead_tasks_task_id'), 'dead_tasks', ['task_id'], unique=True)
    op.create_table('llm_usage',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_agent_id'), 'llm_usage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_company_id'), 'llm_usage', ['company_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_task_id'), 'llm_usage', ['task_id'], unique=False)
    op.create_table('long_memories',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_memories_agent_id'), 'long_memories', ['agent_id'], unique=False)
    op.create_table('part_fitment_evidence',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('part_request_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=24), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_fitment_evidence_article'), 'part_fitment_evidence', ['article'], unique=False)
    op.create_index(op.f('ix_part_fitment_evidence_company_id'), 'part_fitment_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_part_fitment_evidence_part_request_id'), 'part_fitment_evidence', ['part_request_id'], unique=False)
    op.create_index(op.f('ix_part_fitment_evidence_user_id'), 'part_fitment_evidence', ['user_id'], unique=False)
    op.create_index(op.f('ix_part_fitment_evidence_vehicle_id'), 'part_fitment_evidence', ['vehicle_id'], unique=False)
    op.create_table('shadow_comparisons',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('part_request_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_vehicle', sa.Text(), nullable=False),
    sa.Column('ai_part', sa.String(length=240), nullable=False),
    sa.Column('ai_article', sa.String(length=120), nullable=False),
    sa.Column('ai_offer_ids', sa.JSON(), nullable=False),
    sa.Column('ai_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ai_answer', sa.Text(), nullable=False),
    sa.Column('manager_vehicle', sa.Text(), nullable=False),
    sa.Column('manager_part', sa.String(length=240), nullable=False),
    sa.Column('manager_article', sa.String(length=120), nullable=False),
    sa.Column('manager_offer_ids', sa.JSON(), nullable=False),
    sa.Column('manager_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('manager_reply', sa.Text(), nullable=False),
    sa.Column('vehicle_match', sa.Boolean(), nullable=True),
    sa.Column('part_match', sa.Boolean(), nullable=True),
    sa.Column('oem_match', sa.Boolean(), nullable=True),
    sa.Column('offer_overlap', sa.Integer(), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('time_seconds', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_comparisons_company_id'), 'shadow_comparisons', ['company_id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_conversation_id'), 'shadow_comparisons', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_customer_id'), 'shadow_comparisons', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_part_request_id'), 'shadow_comparisons', ['part_request_id'], unique=False)
    op.create_table('supplier_search_runs',
    sa.Column('part_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='supplier_search_status'), nullable=False),
    sa.Column('offers_found', sa.Integer(), nullable=False),
    sa.Column('suppliers_succeeded', sa.Integer(), nullable=False),
    sa.Column('suppliers_failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_search_runs_part_request_id'), 'supplier_search_runs', ['part_request_id'], unique=False)
    op.create_table('task_events',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_agent_id'), 'task_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('agent_feedback',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.Enum('approved_unchanged', 'approved_edited', 'rejected', 'incorrect_fact', 'bad_tone', 'wrong_recommendation', name='agent_feedback_type'), nullable=False),
    sa.Column('original_output', sa.Text(), nullable=True),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_feedback_action_id'), 'agent_feedback', ['action_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_agent_id'), 'agent_feedback', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_company_id'), 'agent_feedback', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_task_id'), 'agent_feedback', ['task_id'], unique=False)
    op.create_table('supplier_offers',
    sa.Column('part_request_id', sa.UUID(), nullable=False),
    sa.Column('search_run_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('part_name', sa.String(length=240), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('is_cross', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('customer_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rank_reasons', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_run_id'], ['supplier_search_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_offers_part_request_id'), 'supplier_offers', ['part_request_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_search_run_id'), 'supplier_offers', ['search_run_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_id'), 'supplier_offers', ['supplier_id'], unique=False)
    op.create_table('supplier_search_attempts',
    sa.Column('search_run_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'skipped', name='supplier_attempt_status'), nullable=False),
    sa.Column('offers_found', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['supplier_search_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_search_attempts_search_run_id'), 'supplier_search_attempts', ['search_run_id'], unique=False)
    op.create_index(op.f('ix_supplier_search_attempts_supplier_id'), 'supplier_search_attempts', ['supplier_id'], unique=False)
    op.create_table('quotes',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('part_request_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('best_offer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'sent', 'accepted', 'rejected', 'expired', 'converted_to_order', name='quote_status'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('quote_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('ai_draft', sa.Text(), nullable=True),
    sa.Column('manager_edited', sa.Text(), nullable=True),
    sa.Column('final_message', sa.Text(), nullable=True),
    sa.Column('guard_status', sa.String(length=16), nullable=False),
    sa.Column('guard_errors', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('auto_send_decision', sa.JSON(), nullable=True),
    sa.Column('auto_sent', sa.Boolean(), nullable=False),
    sa.Column('auto_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['best_offer_id'], ['supplier_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_best_offer_id'), 'quotes', ['best_offer_id'], unique=False)
    op.create_index(op.f('ix_quotes_company_id'), 'quotes', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotes_conversation_id'), 'quotes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_quotes_part_request_id'), 'quotes', ['part_request_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'cancelled', name='approval_status'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='approval_risk_level'), nullable=False),
    sa.Column('requested_by_agent_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_action_id'), 'approval_requests', ['action_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_approved_by_user_id'), 'approval_requests', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_company_id'), 'approval_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_conversation_id'), 'approval_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_quote_id'), 'approval_requests', ['quote_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_rejected_by_user_id'), 'approval_requests', ['rejected_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_requested_by_agent_id'), 'approval_requests', ['requested_by_agent_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_task_id'), 'approval_requests', ['task_id'], unique=False)
    op.create_table('orders',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('part_request_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('new', 'confirmed', 'paid', 'cancelled', name='order_status'), nullable=False),
    sa.Column('tracking_status', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('order_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_conversation_id'), 'orders', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_orders_created_by_user_id'), 'orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_part_request_id'), 'orders', ['part_request_id'], unique=False)
    op.create_index(op.f('ix_orders_quote_id'), 'orders', ['quote_id'], unique=False)
    op.create_table('part_returns',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('part_request_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_request_id'], ['part_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_returns_company_id'), 'part_returns', ['company_id'], unique=False)
    op.create_index(op.f('ix_part_returns_order_id'), 'part_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_part_returns_part_request_id'), 'part_returns', ['part_request_id'], unique=False)
    op.create_index(op.f('ix_part_returns_quote_id'), 'part_returns', ['quote_id'], unique=False)
    op.create_index(op.f('ix_part_returns_supplier_id'), 'part_returns', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_part_returns_vehicle_id'), 'part_returns', ['vehicle_id'], unique=False)
    op.create_table('supplier_fulfillments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('promised_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('promised_delivery_days', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('actual_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_delivery_days', sa.Integer(), nullable=True),
    sa.Column('quantity_delivered', sa.Integer(), nullable=True),
    sa.Column('external_order_id', sa.String(length=80), nullable=True),
    sa.Column('supplier_status', sa.String(length=40), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_fulfillments_company_id'), 'supplier_fulfillments', ['company_id'], unique=False)
    op.create_index(op.f('ix_supplier_fulfillments_external_order_id'), 'supplier_fulfillments', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_fulfillments_offer_id'), 'supplier_fulfillments', ['offer_id'], unique=False)
    op.create_index(op.f('ix_supplier_fulfillments_order_id'), 'supplier_fulfillments', ['order_id'], unique=False)
    op.create_index(op.f('ix_supplier_fulfillments_supplier_id'), 'supplier_fulfillments', ['supplier_id'], unique=False)
    op.create_table('trace_spans',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('span_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('error_kind', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_span_id'], ['trace_spans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_spans_agent_id'), 'trace_spans', ['agent_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_order_id'), 'trace_spans', ['order_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_parent_span_id'), 'trace_spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_supplier_id'), 'trace_spans', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_task_id'), 'trace_spans', ['task_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_trace_id'), 'trace_spans', ['trace_id'], unique=False)
    op.create_index('ix_trace_spans_trace_parent', 'trace_spans', ['trace_id', 'parent_span_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trace_spans_trace_parent', table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_trace_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_task_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_supplier_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_parent_span_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_order_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_agent_id'), table_name='trace_spans')
    op.drop_table('trace_spans')
    op.drop_index(op.f('ix_supplier_fulfillments_supplier_id'), table_name='supplier_fulfillments')
    op.drop_index(op.f('ix_supplier_fulfillments_order_id'), table_name='supplier_fulfillments')
    op.drop_index(op.f('ix_supplier_fulfillments_offer_id'), table_name='supplier_fulfillments')
    op.drop_index(op.f('ix_supplier_fulfillments_external_order_id'), table_name='supplier_fulfillments')
    op.drop_index(op.f('ix_supplier_fulfillments_company_id'), table_name='supplier_fulfillments')
    op.drop_table('supplier_fulfillments')
    op.drop_index(op.f('ix_part_returns_vehicle_id'), table_name='part_returns')
    op.drop_index(op.f('ix_part_returns_supplier_id'), table_name='part_returns')
    op.drop_index(op.f('ix_part_returns_quote_id'), table_name='part_returns')
    op.drop_index(op.f('ix_part_returns_part_request_id'), table_name='part_returns')
    op.drop_index(op.f('ix_part_returns_order_id'), table_name='part_returns')
    op.drop_index(op.f('ix_part_returns_company_id'), table_name='part_returns')
    op.drop_table('part_returns')
    op.drop_index(op.f('ix_orders_quote_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_part_request_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_conversation_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_approval_requests_task_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requested_by_agent_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_rejected_by_user_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_quote_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_conversation_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_company_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approved_by_user_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_quotes_part_request_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_conversation_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_company_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_best_offer_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_supplier_search_attempts_supplier_id'), table_name='supplier_search_attempts')
    op.drop_index(op.f('ix_supplier_search_attempts_search_run_id'), table_name='supplier_search_attempts')
    op.drop_table('supplier_search_attempts')
    op.drop_index(op.f('ix_supplier_offers_supplier_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_search_run_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_part_request_id'), table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index(op.f('ix_agent_feedback_task_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_company_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_agent_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_action_id'), table_name='agent_feedback')
    op.drop_table('agent_feedback')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_agent_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_supplier_search_runs_part_request_id'), table_name='supplier_search_runs')
    op.drop_table('supplier_search_runs')
    op.drop_index(op.f('ix_shadow_comparisons_part_request_id'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_customer_id'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_conversation_id'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_company_id'), table_name='shadow_comparisons')
    op.drop_table('shadow_comparisons')
    op.drop_index(op.f('ix_part_fitment_evidence_vehicle_id'), table_name='part_fitment_evidence')
    op.drop_index(op.f('ix_part_fitment_evidence_user_id'), table_name='part_fitment_evidence')
    op.drop_index(op.f('ix_part_fitment_evidence_part_request_id'), table_name='part_fitment_evidence')
    op.drop_index(op.f('ix_part_fitment_evidence_company_id'), table_name='part_fitment_evidence')
    op.drop_index(op.f('ix_part_fitment_evidence_article'), table_name='part_fitment_evidence')
    op.drop_table('part_fitment_evidence')
    op.drop_index(op.f('ix_long_memories_agent_id'), table_name='long_memories')
    op.drop_table('long_memories')
    op.drop_index(op.f('ix_llm_usage_task_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_company_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_agent_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_dead_tasks_task_id'), table_name='dead_tasks')
    op.drop_index(op.f('ix_dead_tasks_replayed_task_id'), table_name='dead_tasks')
    op.drop_index(op.f('ix_dead_tasks_company_id'), table_name='dead_tasks')
    op.drop_index(op.f('ix_dead_tasks_agent_id'), table_name='dead_tasks')
    op.drop_table('dead_tasks')
    op.drop_index(op.f('ix_agent_actions_task_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_company_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_agent_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_action_type'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_tasks_trace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_replayed_from_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_part_requests_vehicle_id'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_source_message_id'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_customer_id'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_conversation_id'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_company_id'), table_name='part_requests')
    op.drop_table('part_requests')
    op.drop_index(op.f('ix_traces_conversation_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_company_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_short_memories_agent_id'), table_name='short_memories')
    op.drop_table('short_memories')
    op.drop_index(op.f('ix_memory_entries_agent_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_company_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_company_created', table_name='audit_events')
    op.drop_index('ix_audit_events_action_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_tools_agent_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_slug'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_prompt_versions_company_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_agent_kind'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_knowledge_entries_company_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cross_references_target_article'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_source_article'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_company_id'), table_name='cross_references')
    op.drop_table('cross_references')
    op.drop_index(op.f('ix_company_policies_company_id'), table_name='company_policies')
    op.drop_table('company_policies')
    op.drop_index(op.f('ix_catalog_fitments_company_id'), table_name='catalog_fitments')
    op.drop_index(op.f('ix_catalog_fitments_article'), table_name='catalog_fitments')
    op.drop_table('catalog_fitments')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_index(op.f('ix_agents_company_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_public_token'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
