"""add pack config

Revision ID: 4dd25de42969
Revises: 7e95954f104a
Create Date: 2026-08-18 16:09:22.866898

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4dd25de42969'
down_revision: str | None = '7e95954f104a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packs', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packs', 'config')
    # ### end Alembic commands ###
