"""core initial

Revision ID: f3f7d6c38e9c
Revises: 
Create Date: 2026-08-17 11:28:49.268408

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f3f7d6c38e9c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('agent_quota', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('shadow_mode', sa.Boolean(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_public_token'), 'companies', ['public_token'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('agents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('system', 'general', 'specialized', name='agent_type'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'active', 'paused', 'disabled', 'failed', name='agent_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('avg_success_rate', sa.Float(), nullable=False),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_company_id'), 'agents', ['company_id'], unique=False)
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.create_table('company_policies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('pricing_policy', sa.JSON(), nullable=True),
    sa.Column('supplier_policy', sa.JSON(), nullable=True),
    sa.Column('approval_policy', sa.JSON(), nullable=True),
    sa.Column('sales_policy', sa.JSON(), nullable=True),
    sa.Column('security_policy', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_policies_company_id'), 'company_policies', ['company_id'], unique=True)
    op.create_table('customers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_company_id'), 'knowledge_entries', ['company_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('agent_kind', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'agent_kind', 'version', name='uq_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_agent_kind'), 'prompt_versions', ['agent_kind'], unique=False)
    op.create_index(op.f('ix_prompt_versions_company_id'), 'prompt_versions', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_name')
    )
    op.create_index(op.f('ix_agent_tools_agent_id'), 'agent_tools', ['agent_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_action_created', 'audit_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_events_company_created', 'audit_events', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.Enum('ai_active', 'human_active', 'paused', 'closed', name='conversation_mode'), server_default='ai_active', nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_company_id'), 'conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.Enum('short', 'long', 'knowledge', name='memory_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_agent_id'), 'memory_entries', ['agent_id'], unique=False)
    op.create_table('short_memories',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_memories_agent_id'), 'short_memories', ['agent_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('traces',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('root_span_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_span_id'], ['trace_spans.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_company_id'), 'traces', ['company_id'], unique=False)
    op.create_index(op.f('ix_traces_conversation_id'), 'traces', ['conversation_id'], unique=False)
    op.create_table('tasks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'awaiting_routing', 'completed', 'failed', 'cancelled', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('routing_decision', sa.JSON(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('replayed_from_task_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replayed_from_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_replayed_from_task_id'), 'tasks', ['replayed_from_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_trace_id'), 'tasks', ['trace_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='agent_action_risk_level'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'executed', 'failed', 'cancelled', name='agent_action_status'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_agent_actions_action_type'), 'agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_actions_agent_id'), 'agent_actions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_company_id'), 'agent_actions', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_task_id'), 'agent_actions', ['task_id'], unique=False)
    op.create_table('dead_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('exception_kind', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('dead_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_task_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replayed_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_tasks_agent_id'), 'dead_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_dead_tasks_company_id'), 'dead_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_dead_tasks_replayed_task_id'), 'dead_tasks', ['replayed_task_id'], unique=False)
    op.create_index(op.f('ix_dead_tasks_task_id'), 'dead_tasks', ['task_id'], unique=True)
    op.create_table('llm_usage',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_agent_id'), 'llm_usage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_company_id'), 'llm_usage', ['company_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_task_id'), 'llm_usage', ['task_id'], unique=False)
    op.create_table('long_memories',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_memories_agent_id'), 'long_memories', ['agent_id'], unique=False)
    op.create_table('task_events',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_agent_id'), 'task_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('trace_spans',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('span_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('error_kind', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_span_id'], ['trace_spans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_spans_agent_id'), 'trace_spans', ['agent_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_order_id'), 'trace_spans', ['order_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_parent_span_id'), 'trace_spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_supplier_id'), 'trace_spans', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_task_id'), 'trace_spans', ['task_id'], unique=False)
    op.create_index(op.f('ix_trace_spans_trace_id'), 'trace_spans', ['trace_id'], unique=False)
    op.create_index('ix_trace_spans_trace_parent', 'trace_spans', ['trace_id', 'parent_span_id'], unique=False)
    op.create_table('agent_feedback',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.Enum('approved_unchanged', 'approved_edited', 'rejected', 'incorrect_fact', 'bad_tone', 'wrong_recommendation', name='agent_feedback_type'), nullable=False),
    sa.Column('original_output', sa.Text(), nullable=True),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_feedback_action_id'), 'agent_feedback', ['action_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_agent_id'), 'agent_feedback', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_company_id'), 'agent_feedback', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_task_id'), 'agent_feedback', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_feedback_task_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_company_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_agent_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_action_id'), table_name='agent_feedback')
    op.drop_table('agent_feedback')
    op.drop_index('ix_trace_spans_trace_parent', table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_trace_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_task_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_supplier_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_parent_span_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_order_id'), table_name='trace_spans')
    op.drop_index(op.f('ix_trace_spans_agent_id'), table_name='trace_spans')
    op.drop_table('trace_spans')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_agent_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_long_memories_agent_id'), table_name='long_memories')
    op.drop_table('long_memories')
    op.drop_index(op.f('ix_llm_usage_task_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_company_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_agent_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_dead_tasks_task_id'), table_name='dead_tasks')
    op.drop_index(op.f('ix_dead_tasks_replayed_task_id'), table_name='dead_tasks')
    op.drop_index(op.f('ix_dead_tasks_company_id'), table_name='dead_tasks')
    op.drop_index(op.f('ix_dead_tasks_agent_id'), table_name='dead_tasks')
    op.drop_table('dead_tasks')
    op.drop_index(op.f('ix_agent_actions_task_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_company_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_agent_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_action_type'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_tasks_trace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_replayed_from_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_traces_conversation_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_company_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_short_memories_agent_id'), table_name='short_memories')
    op.drop_table('short_memories')
    op.drop_index(op.f('ix_memory_entries_agent_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_company_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_company_created', table_name='audit_events')
    op.drop_index('ix_audit_events_action_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_tools_agent_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_prompt_versions_company_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_agent_kind'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_knowledge_entries_company_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_company_policies_company_id'), table_name='company_policies')
    op.drop_table('company_policies')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_index(op.f('ix_agents_company_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_public_token'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
